[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[general]
live_config_reload = true
import = [
    #"~/.config/alacritty/themes/themes/gruber_darker.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/base16-alacritty/colors/base16-tomorrow-night-eighties-256.toml"
]

[bell]
command = "None"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
startup_mode = "Windowed"
title = "Ora Et Labora"
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 0
y = 0

[keyboard]
